language: java
jdk:
- oraclejdk8
branches:
  only:
  - development
env:
  global:
  - SONATYPE_USERNAME=deployment
  - secure: 4p3u8Cq3fltLsUPo1xeouPlr55emAcONYu0ya2T+gSeUGWhEgUxPD/droW0maxtuzbjLA+gGVjvnkHDCMhorxGNuj8N3UjLWprOj4MBWsgrgdV2+GdqxKlOEOiRACkjgTTWPci++YwbKzRS/R5AlWfprd+Mtqzt9r2w24nbSbC62d/fgZyPNuPIoxtsVYqSx568d91gD6irZkrERps0w0ZJASvw25psUr3T4JIOT0seIF7kVl0ClRG7L1xUyeMEsDKUyEBn5AAPfU072PaJvjtHPiM019Lda2u9vS6H0DgrMgLeWW/ZXTe6PB6p4KvhHzQDlRi7cPhTVUcFXsZZqlTVGXziwaFHykhzyhuhW27DvlyYpqlda2N3go9OcTZLu0GVkQhx6C5D2bu8aWaDps2LqO/MT2MeTZPdh+ZRwNX0d1FMt3uoBXr4x7B7w46PSKg0FCx+dKUdte76ZPDNzyNS5miea1uwzeYxIuyZAqrclIYc3WRTjCTkac8fh7kKwKb3k4OEqSguJOBW9vkp82T9mirff0NjMQYsOAV8E/hi6/rYE6ny+20KjZYvGwDXjfAmaPTAuFTvfZxgV+HiQxRiCrOYbtvu/Xsex11cOGUsQ8OgjeLry2XA2eL29y+t7ga4CN/NFYGhzqBDBo+xDooawWm81Lu56swiBj1s+s8s=

after_success:
- mvn deploy --settings settings.xml -DskipTests=true -B
