language: java

jdk:
  - oraclejdk8

branches:
  only:
  - development

env:
  global:
    - SONATYPE_USERNAME=deployment
  secure: "WD4hK/ahj+Io2s7Y989+lGGlph8vOG+7G5BC/w+krnN5Km+Nr1x0eKJKJh/2FxKbPsSrpCWSkhJL2Kk7OID4V1sMQxZI8YhQRzUyUmXktEkw6uDeTJ3vxWJUDFX3916VtjmvoOzyvVhexymrmADTn3FYpow62WGqbC2bv5436XxgkG4Zva2vqwIGZGy1Q4M1Az7rxBATEJBk2jE6Kht9uXeTd38knhGaUC9mU/F/FZblDEGUexA2lV3DfQ/O5OdvGJd1SMMuHZ8wWw+ypXKq0UhgmDLz4FTIbtga6WGb5rQwpqcNFxUXgC2vNOSk9qiBd4+YAkqXsaFLiFmj1jaDeLR97U7oKMEjjr5/965ZCAjPZSoys81D2G0w5whIf7EkVTO3XI30v+cQWj6hKbOsbL9kb+0KtfUbI9ckgX4bRb7T1ky121zXPCs4+O6TmitYNmItR6bPKgIBgPR4JTLPTiLU01CKDRu/uYj877nTazHkrvhsJpRgL0dLhFDVrjZhlz5QoRsd0RtE6kXyiOHFe4K9LEylxaLic07XBrCF27Il1opB4YgSk6OaHWFefxOSmsgyvp91B6W4uS5Bj6aj1nQEzgzWyFYILDNp/WOubVh/cYXzQbdwktdAvAXNmndmROwPdioZ/rz/1kKma/CtrBhuDMpi7LtpuzcITq88o5E="

after_success:
  - mvn deploy --settings settings.xml -DskipTests=true -B

